### ISSUE TITLE
Build failed (uint8_t)

### ISSUE THREAD

**Issue by floatingpoint-754** [3-manifolds/regina_wheels#2]
I tried building from source as explained in the Readme, since there's no wheel available for Python 3.12 yet. The build fails, and the errors appear to be related to types such as `uint8_t` and `int8_t` not being defined. I am on Linux (x64), and the build was using gcc.

I managed to make it compile by adding `#include <stdint.h>` to every source file containing such types (however, there's probably a simpler way that I'm unaware of). Is this fix correct?

Thanks.

**Comment by NathanDunfield** [comment]
Unfortunately, I don't understand C++ well enough to actually answer your question, but am glad you were able to get it to compile.

We have just posted wheels for Python 3.12 on PyPI, so I'm closing this ticket.
